// The symbol drawn for a grocery item that has no photograph yet.
//
// A symbol says what kind of thing an item is (a fish, a carton of milk, a
// cleaning spray) without pretending to show the product itself. The most
// specific match wins: the item's shape, then its aisle, then its department.
import {
  Apple,
  Baby,
  Banana,
  Bath,
  Bean,
  Beef,
  CakeSlice,
  Candy,
  Carrot,
  Cat,
  Cherry,
  Citrus,
  Coffee,
  Cookie,
  CookingPot,
  Croissant,
  CupSoda,
  Cylinder,
  Dog,
  Donut,
  Droplet,
  Droplets,
  Drumstick,
  Egg,
  EggFried,
  Fish,
  GlassWater,
  Globe,
  Grape,
  Ham,
  IceCreamCone,
  Leaf,
  LeafyGreen,
  Lightbulb,
  Milk,
  Nut,
  Package,
  PawPrint,
  Pill,
  Pizza,
  Popcorn,
  Salad,
  Sandwich,
  Scroll,
  Shirt,
  ShoppingBasket,
  Shrimp,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  SprayCan,
  Sprout,
  Utensils,
  UtensilsCrossed,
  Wheat,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const BY_SHAPE: Record<string, LucideIcon> = {
  banana: Banana,
  citrus: Citrus,
  grapes: Grape,
  berry: Cherry,
  strawberry: Cherry,
  round: Apple,
  pear: Apple,
  leafy: LeafyGreen,
  herb: LeafyGreen,
  floret: Sprout,
  root: Carrot,
  longveg: Carrot,
  egg: Egg,
  coffeebag: Coffee,
  teabox: Leaf,
  shrimp: Shrimp,
  fillet: Fish,
  steak: Beef,
  poultry: Drumstick,
  bacon: Ham,
  sausage: Ham,
  deli: Ham,
  pizza: Pizza,
  croissant: Croissant,
  pastry: Croissant,
  bagel: Donut,
  loaf: Wheat,
  baguette: Wheat,
  bun: Sandwich,
  diaper: Baby,
  toothbrush: Smile,
  spray: SprayCan,
};

const BY_AISLE: Record<string, LucideIcon> = {
  fruit: Apple,
  vegetables: Carrot,
  herbs: Sprout,
  salads: Salad,
  'milk-aisle': Milk,
  'cheese-aisle': Milk,
  'yogurt-aisle': Milk,
  'butter-aisle': Milk,
  'eggs-aisle': Egg,
  'cream-aisle': Milk,
  alternatives: Nut,
  poultry: Drumstick,
  'beef-aisle': Beef,
  'pork-aisle': Ham,
  seafood: Fish,
  deli: Ham,
  'plant-protein': Bean,
  'hot-food': CookingPot,
  'deli-salads': Salad,
  'prepared-meals': UtensilsCrossed,
  'bread-aisle': Wheat,
  buns: Sandwich,
  bagels: Donut,
  tortillas: Wheat,
  'sweet-bakery': Croissant,
  'pasta-aisle': CookingPot,
  'rice-grains': Wheat,
  'canned-veg': Cylinder,
  'canned-protein': Fish,
  'beans-aisle': Bean,
  'soup-broth': Soup,
  sauces: CookingPot,
  oils: Droplet,
  spices: Leaf,
  baking: CakeSlice,
  condiments: Droplets,
  spreads: Nut,
  'world-foods': Globe,
  'cereal-aisle': Wheat,
  'hot-cereal': Soup,
  'breakfast-extras': EggFried,
  chips: Popcorn,
  crackers: Cookie,
  nuts: Nut,
  cookies: Cookie,
  candy: Candy,
  'dried-fruit': Grape,
  'frozen-veg': Snowflake,
  'frozen-fruit': Snowflake,
  'frozen-meals': Pizza,
  'frozen-potato': Snowflake,
  'frozen-seafood': Fish,
  'ice-cream': IceCreamCone,
  'frozen-breakfast': Snowflake,
  water: GlassWater,
  juice: Citrus,
  'soft-drinks': CupSoda,
  'coffee-aisle': Coffee,
  'tea-aisle': Leaf,
  energy: Zap,
  paper: Scroll,
  cleaning: SprayCan,
  laundry: Shirt,
  dish: Utensils,
  storage: Package,
  'home-hardware': Lightbulb,
  hair: Sparkles,
  oral: Smile,
  body: Bath,
  deodorant: SprayCan,
  health: Pill,
  diapers: Baby,
  'baby-food': Baby,
  'baby-care': Baby,
  dog: Dog,
  cat: Cat,
};

const BY_DEPARTMENT: Record<string, LucideIcon> = {
  produce: Apple,
  dairy: Milk,
  meat: Beef,
  deli: Sandwich,
  bakery: Croissant,
  pantry: CookingPot,
  breakfast: Coffee,
  snacks: Cookie,
  frozen: Snowflake,
  beverages: CupSoda,
  household: SprayCan,
  personal: Bath,
  baby: Baby,
  pet: PawPrint,
};

export type GlyphSource = {shape?: string; aisleId?: string; departmentId?: string};

/** The symbol for an item, falling back to a basket for anything unmatched. */
export function glyphFor(item?: GlyphSource | null): LucideIcon {
  if (!item) return ShoppingBasket;
  return (
    (item.shape && BY_SHAPE[item.shape]) ||
    (item.aisleId && BY_AISLE[item.aisleId]) ||
    (item.departmentId && BY_DEPARTMENT[item.departmentId]) ||
    ShoppingBasket
  );
}

export const departmentGlyph = (departmentId: string): LucideIcon =>
  BY_DEPARTMENT[departmentId] ?? ShoppingBasket;
export const aisleGlyph = (aisleId: string, departmentId: string): LucideIcon =>
  BY_AISLE[aisleId] ?? departmentGlyph(departmentId);
